version: '3.4'
services:
    client:
        build: ./crawler_client
        container_name: "crawler_client"
        ports:
            - 8080:8080
        volumes:
            - ./crawler_client:/usr/src/app
        depends_on:
            - mongodb

    crawler_app:
        build: ./crawler_app
        container_name: "crawler_app"
        ports:
            - 65432:65432
        volumes:
            - ./crawler_app:/usr/src/app
        depends_on:
            - mongodb
            
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./mongo_data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet